ByteBrew-Coffee-Roasters/Pages/Orders/List.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ByteBrew_Coffee_Roasters.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ByteBrew_Coffee_Roasters.Pages.Orders
{
    [Authorize(Roles = "Менеджер, Админ")]
    public class ListModel : PageModel
    {
        private readonly ByteBrew_Coffee_Roasters.Data.ApplicationDbContext _context;

        public ListModel(ByteBrew_Coffee_Roasters.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<Order> Orders { get; set; } = new List<Order>();

        public async Task OnGetAsync()
        {
            Orders = await _context.Orders
                .Where(x => x.Status == "Создан")
                .Include(x => x.Products)
                .ThenInclude(x => x.Product)
                .OrderBy(x => x.DateTime)
                .ToListAsync();
        }

        public async Task<IActionResult> OnPostOrderCompleteAsync(Guid orderId)
        {
            Order? order = await _context.Orders.FindAsync([orderId]);

            if (order != null)
            {
                order.Status = "Выполнен";
                await _context.SaveChangesAsync();
            }
            return RedirectToPage();
        }
    }
}

ByteBrew-Coffee-Roasters/Pages/Products/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ByteBrew_Coffee_Roasters.Data.Models;
using Microsoft.AspNetCore.Authorization;

namespace ByteBrew_Coffee_Roasters.Pages.Products
{
    [Authorize(Roles = "Менеджер, Админ")]
    public class CreateModel : PageModel
    {
        private readonly ByteBrew_Coffee_Roasters.Data.ApplicationDbContext _context;

        public CreateModel(ByteBrew_Coffee_Roasters.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Product Product { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Products.Add(Product);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

ByteBrew-Coffee-Roasters/Pages/Products/CreateReview.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ByteBrew_Coffee_Roasters.Data;
using ByteBrew_Coffee_Roasters.Data.Models;

namespace ByteBrew_Coffee_Roasters.Pages.Products
{
    public class CreateReviewModel : PageModel
    {
        private readonly ByteBrew_Coffee_Roasters.Data.ApplicationDbContext _context;

        public CreateReviewModel(ByteBrew_Coffee_Roasters.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Name");
            return Page();
        }

        [BindProperty]
        public ProductReview ProductReview { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.ProductReviews.Add(ProductReview);
            await _context.SaveChangesAsync();

            return Redirect("/Products/CreateReview");
        }
    }
}

ByteBrew-Coffee-Roasters/Pages/Products/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ByteBrew_Coffee_Roasters.Data.Models;
using Microsoft.AspNetCore.Authorization;

namespace ByteBrew_Coffee_Roasters.Pages.Products
{
    [Authorize(Roles = "Менеджер, Админ")]
    public class DeleteModel : PageModel
    {
        private readonly ByteBrew_Coffee_Roasters.Data.ApplicationDbContext _context;

        public DeleteModel(ByteBrew_Coffee_Roasters.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Product Product { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FirstOrDefaultAsync(m => m.Id == id);

            if (product == null)
            {
                return NotFound();
            }
            else
            {
                Product = product;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product != null)
            {
                Product = product;
                _context.Products.Remove(Product);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

ByteBrew-Coffee-Roasters/Pages/Products/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ByteBrew_Coffee_Roasters.Data.Models;
using Microsoft.AspNetCore.Authorization;

namespace ByteBrew_Coffee_Roasters.Pages.Products
{
    [Authorize(Roles = "Менеджер, Админ")]
    public class DetailsModel : PageModel
    {
        private readonly ByteBrew_Coffee_Roasters.Data.ApplicationDbContext _context;

        public DetailsModel(ByteBrew_Coffee_Roasters.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public Product Product { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            else
            {
                Product = product;
            }
            return Page();
        }
    }
}

ByteBrew-Coffee-Roasters/Pages/Products/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ByteBrew_Coffee_Roasters.Data.Models;
using Microsoft.AspNetCore.Authorization;

namespace ByteBrew_Coffee_Roasters.Pages.Products
{
    [Authorize(Roles = "Менеджер, Админ")]
    public class IndexModel : PageModel
    {
        private readonly ByteBrew_Coffee_Roasters.Data.ApplicationDbContext _context;

        public IndexModel(ByteBrew_Coffee_Roasters.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<Product> Product { get;set; } = default!;

        public async Task OnGetAsync()
        {
            Product = await _context.Products.ToListAsync();
        }
    }
}

ByteBrew-Coffee-Roasters/Pages/Products/List.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ByteBrew_Coffee_Roasters.Data.Models;
using Microsoft.AspNetCore.Mvc;

namespace ByteBrew_Coffee_Roasters.Pages.Products
{
    public class ListModel(ByteBrew_Coffee_Roasters.Data.ApplicationDbContext context) : PageModel
    {
        private readonly ByteBrew_Coffee_Roasters.Data.ApplicationDbContext _context = context;

        public IList<Product> Products { get; set; } = context.Products.ToList();
        public const string CartSessionKey = "CartId";

        public async Task OnGetAsync()
        {
            Products = await _context.Products.ToListAsync();

            var cartItems = GetCartItems();
            foreach (var product in Products)
            {
                var cartItem = cartItems.FirstOrDefault(x => x.ProductId == product.Id);

                if (cartItem == null)
                {
                    product.QuantityInCart = 0;
                }
                else
                {
                    product.QuantityInCart = cartItem.Quantity;
                }
            }
        }

        public async Task<RedirectResult> OnPostAddToCart(Guid productId, string returnUrl)
        {
            // ID корзины из браузера           
            Guid ShoppingCartId = GetCartId();

            var cartItem = await _context.ShoppingCartItems.SingleOrDefaultAsync(
                c => c.CartId == ShoppingCartId
                && c.ProductId == productId);

            if (cartItem == null)
            {
                // Создаем новый               
                cartItem = new CartItem
                {
                    ItemId = Guid.NewGuid(),
                    ProductId = productId,
                    CartId = ShoppingCartId,
                    Product = _context.Products.SingleOrDefault(p => p.Id == productId),
                    Quantity = 1,
                    DateCreated = DateTime.Now
                };

                await _context.ShoppingCartItems.AddAsync(cartItem);
            }
            else
            {
                // Если есть в корзине, то количество++                
                cartItem.Quantity++;
                Products.Single(x => x.Id == productId).QuantityInCart++;
            }
            await _context.SaveChangesAsync();
            return RedirectPermanent(returnUrl);
        }

        public async Task<RedirectResult> OnPostDecreaseFromCart(Guid productId, string returnUrl)
        {
            // ID корзины из браузера           
            Guid ShoppingCartId = GetCartId();

            var cartItem = await _context.ShoppingCartItems.SingleOrDefaultAsync(
                c => c.CartId == ShoppingCartId
                && c.ProductId == productId);

            if (cartItem != null)
            {
                // Если остался один, то удаляем
                if (cartItem.Quantity == 1)
                {
                    _context.ShoppingCartItems.Remove(cartItem);
                }
                // Иначе отнимаем один из количества
                else
                {
                    cartItem.Quantity--;
                    Products.Single(x => x.Id == productId).QuantityInCart--;
                }
                await _context.SaveChangesAsync();
            }

            return RedirectPermanent(returnUrl);
        }

        public async Task<RedirectResult> OnPostRemoveFromCart(Guid productId, string returnUrl)
        {
            // ID корзины из браузера        
            Guid ShoppingCartId = GetCartId();

            var cartItem = await _context.ShoppingCartItems
                .SingleOrDefaultAsync(x => x.CartId == ShoppingCartId && x.ProductId == productId);

            if (cartItem != null)
            {
                _context.ShoppingCartItems.Remove(cartItem);
                await _context.SaveChangesAsync();
            }

            return RedirectPermanent(returnUrl);
        }

        public Guid GetCartId()
        {
            if (HttpContext.Session.Get(CartSessionKey) == null)
            {
                if (!string.IsNullOrWhiteSpace(HttpContext.User.Identity!.Name))
                {
                    Guid userId = new (HttpContext.User.Claims.First(x => x.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier").Value);
                    HttpContext.Session.Set(CartSessionKey, userId.ToByteArray());
                }
                else
                {
                    // Анонимный гость
                    Guid tempCartId = Guid.NewGuid();
                    HttpContext.Session.Set(CartSessionKey, tempCartId.ToByteArray());
                }
            }

            return new Guid(HttpContext.Session.Get(CartSessionKey)!);
        }

        public List<CartItem> GetCartItems()
        {
            Guid ShoppingCartId = GetCartId();

            return _context.ShoppingCartItems.Where(c => c.CartId == ShoppingCartId).ToList();
        }
    }
}

ByteBrew-Coffee-Roasters/Pages/Products/ShoppingCart.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ByteBrew_Coffee_Roasters.Data.Models;
using Microsoft.AspNetCore.Mvc;

namespace ByteBrew_Coffee_Roasters.Pages.Products
{
    public class ShoppingCartModel : PageModel
    {
        private readonly ByteBrew_Coffee_Roasters.Data.ApplicationDbContext _context;

        public ShoppingCartModel(ByteBrew_Coffee_Roasters.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<CartItem> CartItems { get; set; } = new List<CartItem>();
        public const string CartSessionKey = "CartId";

        public async Task OnGetAsync()
        {
            CartItems = await _context.ShoppingCartItems
                .Where(x => x.CartId == GetCartId())
                .Include(c => c.Product)
                .ToListAsync();
        }

        public Guid GetCartId()
        {
            if (HttpContext.Session.Get(CartSessionKey) == null)
            {
                if (!string.IsNullOrWhiteSpace(HttpContext.User.Identity!.Name))
                {
                    Guid userId = new(HttpContext.User.Claims.First(x => x.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier").Value);
                    HttpContext.Session.Set(CartSessionKey, userId.ToByteArray());
                }
                else
                {
                    Guid tempCartId = Guid.NewGuid();
                    HttpContext.Session.Set(CartSessionKey, tempCartId.ToByteArray());
                }
            }

            return new Guid(HttpContext.Session.Get(CartSessionKey)!);
        }

        public async Task<IActionResult> OnPostAddToCart(Guid productId)
        {
            Guid ShoppingCartId = GetCartId();

            var cartItem = await _context.ShoppingCartItems.SingleOrDefaultAsync(
                c => c.CartId == ShoppingCartId && c.ProductId == productId);

            if (cartItem == null)
            {
                cartItem = new CartItem
                {
                    ItemId = Guid.NewGuid(),
                    ProductId = productId,
                    CartId = ShoppingCartId,
                    Product = await _context.Products.SingleOrDefaultAsync(p => p.Id == productId),
                    Quantity = 1,
                    DateCreated = DateTime.Now
                };

                await _context.ShoppingCartItems.AddAsync(cartItem);
            }
            else
            {
                cartItem.Quantity++;
            }
            await _context.SaveChangesAsync();
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostDecreaseFromCart(Guid productId)
        {
            Guid ShoppingCartId = GetCartId();

            var cartItem = await _context.ShoppingCartItems.SingleOrDefaultAsync(
                c => c.CartId == ShoppingCartId && c.ProductId == productId);

            if (cartItem != null)
            {
                if (cartItem.Quantity == 1)
                {
                    _context.ShoppingCartItems.Remove(cartItem);
                }
                else
                {
                    cartItem.Quantity--;
                }
                await _context.SaveChangesAsync();
            }

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostRemoveFromCart(Guid productId)
        {
            Guid ShoppingCartId = GetCartId();

            var cartItem = await _context.ShoppingCartItems
                .SingleOrDefaultAsync(x => x.CartId == ShoppingCartId && x.ProductId == productId);

            if (cartItem != null)
            {
                _context.ShoppingCartItems.Remove(cartItem);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostMakeOrder()
        {
            Guid ShoppingCartId = GetCartId();

            var cartItems = await _context.ShoppingCartItems
                .Where(x => x.CartId == ShoppingCartId).ToListAsync();

            if (cartItems != null)
            {
                bool isUserAuthorizated = await _context.Users.AnyAsync(x => x.Id == ShoppingCartId);

                Order newOrder = new("Создан");
                if (isUserAuthorizated)
                    newOrder = new("Создан", ShoppingCartId);

                foreach (var item in cartItems)
                {
                    newOrder.Products.Add(new OrderItem(item.ProductId, item.Quantity));
                }
                await _context.Orders.AddAsync(newOrder);

                _context.ShoppingCartItems.RemoveRange(cartItems);

                await _context.SaveChangesAsync();
            }

            return RedirectToPage();
        }
    }
}

ByteBrew-Coffee-Roasters/Pages/Products/Create.cshtml
@page
@model ByteBrew_Coffee_Roasters.Pages.Products.CreateModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Создать</h1>

<h4>Продукт</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Product.Name" class="control-label"></label>
                <input asp-for="Product.Name" class="form-control" />
                <span asp-validation-for="Product.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.Description" class="control-label"></label>
                <input asp-for="Product.Description" class="form-control" />
                <span asp-validation-for="Product.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.Price" class="control-label"></label>
                <input asp-for="Product.Price" class="form-control" />
                <span asp-validation-for="Product.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.Image" class="control-label"></label>
                <input asp-for="Product.Image" class="form-control" />
                <span asp-validation-for="Product.Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Вернуться к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ByteBrew-Coffee-Roasters/Pages/Products/CreateReview.cshtml
@page
@model ByteBrew_Coffee_Roasters.Pages.Products.CreateReviewModel

@{
    ViewData["Title"] = "CreateReview";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="~/css/create_review.css" asp-append-version="true" />

<h1>Отзыв о продукте</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductReview.ProductId" class="control-label">Продукт</label>
                <select asp-for="ProductReview.ProductId" class ="form-control" asp-items="ViewBag.ProductId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ProductReview.Text" class="control-label">Отзыв</label>
                <textarea asp-for="ProductReview.Text" class="form-control" rows="3"></textarea>
                <span asp-validation-for="ProductReview.Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Отправить отзыв" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ByteBrew-Coffee-Roasters/Pages/Products/Delete.cshtml
@page
@model ByteBrew_Coffee_Roasters.Pages.Products.DeleteModel

@{
    ViewData["Title"] = "Удалить";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Удаление</h1>

<h3>Вы действительно хотите удалить продукт?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.Image)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.Image)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Product.Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-page="./Index">Вернуться к списку</a>
    </form>
</div>

ByteBrew-Coffee-Roasters/Pages/Products/Details.cshtml
@page
@model ByteBrew_Coffee_Roasters.Pages.Products.DetailsModel

@{
    ViewData["Title"] = "Продукт";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="~/css/products.css" asp-append-version="true" />

<h1>Детали</h1>

<div>
    <h4>Продукт</h4>
    <hr />
    <div class="row">
        <div class="col-md-6">
            <dl>
                <dt class="product-label">Название</dt>
                <dd class="product-details">@Html.DisplayFor(model => model.Product.Name)</dd>
                <dt class="product-label">Описание</dt>
                <dd class="product-details">@Html.DisplayFor(model => model.Product.Description)</dd>
                <dt class="product-label">Цена</dt>
                <dd class="product-details">@Html.DisplayFor(model => model.Product.Price)</dd>
            </dl>
        </div>
        <div class="col-md-6">
            <img src="@Model.Product.Image" style="max-width: 100%; max-height: auto;" />
        </div>
    </div>
</div>
<a asp-page="./Edit" asp-route-id="@Model.Product.Id">Изменить</a> |
<a asp-page="./Index">Вернуться к списку</a>
</div>

ByteBrew-Coffee-Roasters/Pages/Products/Edit.cshtml
@page
@model ByteBrew_Coffee_Roasters.Pages.Products.EditModel

@{
    ViewData["Title"] = "Редактирование";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="~/css/products.css" asp-append-version="true" />

<h1>Изменение</h1>

<h4>Продукт</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Product.Id" />
            <div class="form-group">
                <label asp-for="Product.Name" class="control-label">Название</label>
                <input asp-for="Product.Name" class="form-control" />
                <span asp-validation-for="Product.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.Description" class="control-label">Описание</label>
                <input asp-for="Product.Description" class="form-control" />
                <span asp-validation-for="Product.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.Price" class="control-label">Цена</label>
                <input asp-for="Product.Price" class="form-control" />
                <span asp-validation-for="Product.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.Image" class="control-label">Изображение</label>
                <input asp-for="Product.Image" class="form-control" />
                <span asp-validation-for="Product.Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Вернуться к списку</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ByteBrew-Coffee-Roasters/Pages/Products/Index.cshtml
@page
@model ByteBrew_Coffee_Roasters.Pages.Products.IndexModel

@{
    ViewData["Title"] = "Продукты";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="~/css/products.css" asp-append-version="true" />
<h1>Продукты</h1>

<button class="btn btn-primary" id="reviews">
    <a class="nav-link text-white" asp-area="" asp-page="/Products/ListReview">Отзывы</a>
</button>

<table class="table">
    <thead>
        <tr>
            <th>
                Название
            </th>
            <th>
                Описание 
            </th>
            <th>
                Цена 
            </th>
            <th>
                Изображение 
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Product)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td style="white-space: nowrap; overflow:hidden;text-overflow: ellipsis; max-width: 250px;">
                    @Html.DisplayFor(modelItem => item.Image)
                </td>
                <td style="white-space:nowrap">
                    <a asp-page="./Edit" asp-route-id="@item.Id">Изменить</a> |
                    <a asp-page="./Details" asp-route-id="@item.Id">Подробнее</a> |
                    <a asp-page="./Delete" asp-route-id="@item.Id">Удалить</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<p>
    <a asp-page="Create">Добавить продукт</a>
</p>

ByteBrew-Coffee-Roasters/Pages/Products/ShoppingCart.cshtml
@page
@model ByteBrew_Coffee_Roasters.Pages.Products.ShoppingCartModel

@{
    ViewData["Title"] = "Корзина";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="~/css/shopping_cart.css" asp-append-version="true" />

<h1>Корзина покупок</h1>

<div id="cart" class="d-flex flex-column align-items-center">
    @if (Model.CartItems.Count > 0)
    {
        foreach (var item in Model.CartItems)
        {
            <div class="card flex-row align-items-center p-3 m-2" style="max-width: 600px; width: 100%;">
                <div class="flex-grow-1 d-flex align-items-center">
                    <img src="@item.Product!.Image" class="card-img-left" style="width: 100px; height: auto; margin-right: 20px;" />
                    <div>
                        <div class="card-title fw-bolder fs-4">@item.Product.Name</div>
                        <div class="card-subtitle text-secondary fs-6">@item.Product.Description</div>
                        <div class="fw-bold fs-4">@item.Product.Price ₽</div>
                    </div>
                </div>
                <div class="d-flex flex-column mt-2">
                    <div class="d-flex flex-row justify-content-around">
                        <form method="post" data-ajax="true" asp-page-handler="DecreaseFromCart">
                            @Html.Hidden("productId", item.ProductId)
                            <button type="submit" class="btn btn-secondary">-</button>
                        </form>
                        <h3>@item.Quantity шт</h3>
                        <form method="post" data-ajax="true" asp-page-handler="AddToCart">
                            @Html.Hidden("productId", item.ProductId)
                            <button type="submit" class="btn btn-secondary">+</button>
                        </form>
                    </div>
                    <div class="d-flex justify-content-center mt-2">
                        <form method="post" data-ajax="true" asp-page-handler="RemoveFromCart">
                            @Html.Hidden("productId", item.ProductId)
                            <button type="submit" class="btn btn-danger">
                                <i class="fas fa-trash-alt">Удалить все</i>
                            </button>
                        </form>
                    </div>
                </div>
            </div>


        }
        <h4>Итого к оплате: @Model.CartItems.Sum(x => x.Quantity * x.Product!.Price) руб</h4>

        <form method="post" data-ajax="true" asp-page-handler="MakeOrder" class="mt-4">
            <button type="submit" class="btn btn-primary">Оформить заказ</button>
        </form>
    }
    else
    {
        <h1>В корзине пока нет товаров</h1>
    }

</div>


<div id="status-message" class="alert alert-success mt-3" role="alert" style="display:none;">
    
</div>

<script>
    $(document).ready(function () {
        function updateCart() {
            $.ajax({
                url: window.location.href,
                method: 'GET',
                success: function (response) {
                    var parsedHTML = $(response);
                    var newCartContent = parsedHTML.find('#cart').html();
                    $('#cart').html(newCartContent);
                },
                error: function (xhr, status, error) {
                    console.error('Error:', error);
                }
            });
        }

        $(document).on('submit', 'form[data-ajax="true"]', function (event) {
            event.preventDefault();
            var $form = $(this);
            $.ajax({
                url: $form.attr('action'),
                method: $form.attr('method'),
                data: $form.serialize(),
                success: function (response) {
                    if ($form[0].action.includes('handler=MakeOrder')) {
                        $('#status-message').text('Успешно. Скоро начнем собирать ваш заказ!').show();
                        updateCart();
                    } else {
                        updateCart();
                    }
                },
                error: function (xhr, status, error) {
                        console.error('Error:', error);
                    }
                });
            });
        });
</script>