ByteBrew-Coffee-Roasters/Pages/Orders/List.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ByteBrew_Coffee_Roasters.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ByteBrew_Coffee_Roasters.Pages.Orders
{
    [Authorize(Roles = "Менеджер, Админ")]
    public class ListModel : PageModel
    {
        private readonly ByteBrew_Coffee_Roasters.Data.ApplicationDbContext _context;

        public ListModel(ByteBrew_Coffee_Roasters.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<Order> Orders { get; set; } = new List<Order>();

        public async Task OnGetAsync()
        {
            Orders = await _context.Orders
                .Where(x => x.Status == "Создан")
                .Include(x => x.Products)
                .ThenInclude(x => x.Product)
                .OrderBy(x => x.DateTime)
                .ToListAsync();
        }

        public async Task<IActionResult> OnPostOrderCompleteAsync(Guid orderId)
        {
            Order? order = await _context.Orders.FindAsync([orderId]);

            if (order != null)
            {
                order.Status = "Выполнен";
                await _context.SaveChangesAsync();
            }
            return RedirectToPage();
        }
    }
}

ByteBrew-Coffee-Roasters/Pages/Products/List.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ByteBrew_Coffee_Roasters.Data.Models;
using Microsoft.AspNetCore.Mvc;

namespace ByteBrew_Coffee_Roasters.Pages.Products
{
    public class ListModel(ByteBrew_Coffee_Roasters.Data.ApplicationDbContext context) : PageModel
    {
        private readonly ByteBrew_Coffee_Roasters.Data.ApplicationDbContext _context = context;

        public IList<Product> Products { get; set; } = context.Products.ToList();
        public const string CartSessionKey = "CartId";

        public async Task OnGetAsync()
        {
            Products = await _context.Products.ToListAsync();

            var cartItems = GetCartItems();
            foreach (var product in Products)
            {
                var cartItem = cartItems.FirstOrDefault(x => x.ProductId == product.Id);

                if (cartItem == null)
                {
                    product.QuantityInCart = 0;
                }
                else
                {
                    product.QuantityInCart = cartItem.Quantity;
                }
            }
        }

        public async Task<RedirectResult> OnPostAddToCart(Guid productId, string returnUrl)
        {
            // ID корзины из браузера           
            Guid ShoppingCartId = GetCartId();

            var cartItem = await _context.ShoppingCartItems.SingleOrDefaultAsync(
                c => c.CartId == ShoppingCartId
                && c.ProductId == productId);

            if (cartItem == null)
            {
                // Создаем новый               
                cartItem = new CartItem
                {
                    ItemId = Guid.NewGuid(),
                    ProductId = productId,
                    CartId = ShoppingCartId,
                    Product = _context.Products.SingleOrDefault(p => p.Id == productId),
                    Quantity = 1,
                    DateCreated = DateTime.Now
                };

                await _context.ShoppingCartItems.AddAsync(cartItem);
            }
            else
            {
                // Если есть в корзине, то количество++                
                cartItem.Quantity++;
                Products.Single(x => x.Id == productId).QuantityInCart++;
            }
            await _context.SaveChangesAsync();
            return RedirectPermanent(returnUrl);
        }

        public async Task<RedirectResult> OnPostDecreaseFromCart(Guid productId, string returnUrl)
        {
            // ID корзины из браузера           
            Guid ShoppingCartId = GetCartId();

            var cartItem = await _context.ShoppingCartItems.SingleOrDefaultAsync(
                c => c.CartId == ShoppingCartId
                && c.ProductId == productId);

            if (cartItem != null)
            {
                // Если остался один, то удаляем
                if (cartItem.Quantity == 1)
                {
                    _context.ShoppingCartItems.Remove(cartItem);
                }
                // Иначе отнимаем один из количества
                else
                {
                    cartItem.Quantity--;
                    Products.Single(x => x.Id == productId).QuantityInCart--;
                }
                await _context.SaveChangesAsync();
            }

            return RedirectPermanent(returnUrl);
        }

        public async Task<RedirectResult> OnPostRemoveFromCart(Guid productId, string returnUrl)
        {
            // ID корзины из браузера        
            Guid ShoppingCartId = GetCartId();

            var cartItem = await _context.ShoppingCartItems
                .SingleOrDefaultAsync(x => x.CartId == ShoppingCartId && x.ProductId == productId);

            if (cartItem != null)
            {
                _context.ShoppingCartItems.Remove(cartItem);
                await _context.SaveChangesAsync();
            }

            return RedirectPermanent(returnUrl);
        }

        public Guid GetCartId()
        {
            if (HttpContext.Session.Get(CartSessionKey) == null)
            {
                if (!string.IsNullOrWhiteSpace(HttpContext.User.Identity!.Name))
                {
                    Guid userId = new (HttpContext.User.Claims.First(x => x.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier").Value);
                    HttpContext.Session.Set(CartSessionKey, userId.ToByteArray());
                }
                else
                {
                    // Анонимный гость
                    Guid tempCartId = Guid.NewGuid();
                    HttpContext.Session.Set(CartSessionKey, tempCartId.ToByteArray());
                }
            }

            return new Guid(HttpContext.Session.Get(CartSessionKey)!);
        }

        public List<CartItem> GetCartItems()
        {
            Guid ShoppingCartId = GetCartId();

            return _context.ShoppingCartItems.Where(c => c.CartId == ShoppingCartId).ToList();
        }
    }
}

ByteBrew-Coffee-Roasters/Pages/Orders/List.cshtml
@page
@model ByteBrew_Coffee_Roasters.Pages.Orders.ListModel
@{
    ViewData["Title"] = "Заказы";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}


<link rel="stylesheet" href="~/css/orders.css" asp-append-version="true" />
<h3>Заказы</h3>

<table class="table" id="orders">
    <thead>
        <tr>
            <th>
                Тип заказчика
                @* @Html.DisplayNameFor(model => model.Orders[0].CustomerType) *@
            </th>
            <th>
                Дата и время заказа
                @* @Html.DisplayNameFor(model => model.Orders[0].DateTime) *@
            </th>
            <th>
                Статус
                @* @Html.DisplayNameFor(model => model.Orders[0].Status) *@
            </th>
            <th>
                Продукты
                @* @Html.DisplayNameFor(model => model.Orders[0].Products) *@
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Orders) {
        <tr>
            <td>
                @(item.CustomerType.ToString() == "Anonymous" ? "Анонимный" : "Авторизованный")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                <ul>
                    @foreach (var product in item.Products)
                    {
                        <li>@product.Product!.Name - @product.Quantity шт</li>
                    }
                </ul>
            </td>
            <td>
                <form method="post" data-ajax="true" asp-page-handler="OrderComplete">
                    @Html.Hidden("orderId", item.Id)
                    <button type="submit" class="btn btn-primary">
                        <i class="fas fa-trash-alt">Выполнен</i>
                    </button>
                </form>
            </td>
        </tr>
}
    </tbody>
</table>

<script>
    $(document).ready(function () {
        function updateOrders() {
            $.ajax({
                url: window.location.href,
                method: 'GET',
                success: function (response) {
                    var parsedHTML = $(response);
                    var newCartContent = parsedHTML.find('#orders').html();
                    $('#orders').html(newCartContent);
                },
                error: function (xhr, status, error) {
                    console.error('Error:', error);
                }
            });
        }

        $(document).on('submit', 'form[data-ajax="true"]', function (event) {
            event.preventDefault();
            var $form = $(this);
            $.ajax({
                url: $form.attr('action'),
                method: $form.attr('method'),
                data: $form.serialize(),
                success: function (response) {
                    updateOrders();
                },
                error: function (xhr, status, error) {
                    console.error('Error:', error);
                }
            });
        });
    });
</script>